### ISSUE TITLE
DOS installation discussion

### ISSUE THREAD

**Issue by rderooy** [Wengier/dosbox-x-wiki#1]
Let's start a discussion thread here...

My first one. You changed a line to read:
- If you need to access a CD or DVD drive you need to load a IDE or ASPI (or even SATA/USB) CD/DVD driver and MSCDEX

How would you load a ASPI or SATA/USB driver in DOSBox? DOSBox has no way to pass-through for native devices like SCSI, SATA or USB, and it has no way to emulate SCSI, SATA or USB either. So you would never use such a driver (if they even existed for DOS). Instead the emulated CD/DVD drive will always be a IDE/PATA device, and as such the user needs to load a IDE/PATA driver.

It would be cool if DOSBox-X would get the ability to pass-through USB devices, but more for later Win9x versions. Something like a Adaptec or BusLogic SCSI controller emulation would also be cool, but of very little benefit, as other then operating systems like early OS/2 and NT versions there is little that really benefits from such support.

**Comment by Wengier** [comment]
@rderooy Oops! I misread that part as disadvantages of booting regular DOS in a real system rather than booting it inside DOSBox-X. In a real DOS system, you will need to load the appropriate interface for the CD/DVD drive of course, including PATA, SATA, SCSI, or USB. Since I have been watching recent developments in the DOS world, I know very well that they all exist. For example, GCDROM.SYS can be used for SATA CD/DVD drives in DOS, and USBASPI.SYS+USBCD.SYS can be used for USB CD/DVD drives in DOS. But you are certainly right at this time DOSBox-X does not emulate SATA, SCSI or USB CD/DVD drives, so you never need to use such as driver inside DOSBox-X currently. In any case, thanks for the correction.

**Comment by rderooy** [comment]
I'm starting to think that the file needs to be split up as it is getting rather large, which by itself can become confusing both for us and for the users. Also because MarkDown has to automated TOC feature (like the __TOC__ tag you can use on MediaWiki sites).

I have not even touched on PC-DOS 4 or DOS versions 5 or later...

So perhaps a generic page with various generic topics and then links to sub-pages for the different install instructions.

e.g.

- DOS 2.0-3.21
- DOS 3.3 (should perhaps just be merged into the 2.0-3.21 page)
- PC-DOS 4
- MS-DOS 4
- ...

I'm also not quite sure how to handle the later PC-DOS versions. There is no mention of PC-DOS 6,7 or 2000 yet. I think that PC-DOS 5 and MS-DOS 5 where pretty much the same, but they diverged after? Need to double check.

**Comment by Wengier** [comment]
@rderooy It is probably a good idea to split the page when it becomes very large. Since MS-DOS and PC-DOS are very similar up to and including version 5.x, I think perhaps they can be discussed together a way like this:

* DOS 1.0-3.3
* DOS 4.0-5.x
* PC-DOS 6.x
* PC-DOS 7.x/2000
* MS-DOS 6.x
* MS-DOS 7.x
